info:
  version: "20230517.01"

theme: jekyll-theme-leap-day
title: KapreSoft
name: KapreSoft.com
description: "Thank you for unblocking ads; your support allows us to continue delivering free, high-quality content that truly matters to you."
layout: kapresoft
exclude:
  - ".notes"
  - "docs/*"
  - "README*.md"
  - "*.sh"
  - "*.http"
  - "http-client.env.json"
  - "jekyll-theme-leap-day.gemspec"
  - "README.md"
  - "*.code-workspace"
  - ".idea"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

related:
  max-count: 10

collections:
  blog:
    output: true

# set to "dev" so that analytics and adds won't show
env: prod

# OLD Analytics Tracking ID (Deprecated)
# google_analytics: UA-123953282-1

# ----------------
# Google Analytics (V4)
ga:
  enable: true
  tracking_id: G-1EG60WX50K

show_google_ads: true
# toggle ads on the homepage feed
show_google_ads_feed: true
show_banner: false

excerpt_separator: <!--excerpt-->

# ---------------
# highlighterjs
#  - no line number supper
# Themes: https://github.com/highlightjs/highlight.js/tree/main/src/styles
highlighterjs:
    default_theme: androidstudio

github:
    is_project_page: true
    owner_url: /about-antonio-lagnada.html
    owner_name: KapreSoft (Antonio Lagnada)

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-default-layout

whitelist:
  - c_merge_list
  - c_whitespace_filter

last-modified-at:
  date-format: '%d-%b-%y %T %z'

# seo-tag
author:
  name: Antonio Lagnada
  twitter: deloy72
logo: https://cdngh.kapresoft.com/img/kapresoft1-210x-09aaa6e.png

twitter:
  username: deloy72
  card: summary

# See:
#  - https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md
#  - https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - values:
      image: https://cdngh.kapresoft.com/img/kapresoft1-210x-09aaa6e.png
