theme: jekyll-theme-leap-day
title: KapreSoft
name: KapreSoft.com
description: The Java Blogger by Antonio Lagnada
google_analytics: UA-123953282-1

show_google_ads: true
show_banner: false

excerpt_separator: <!--excerpt-->

github:
    is_project_page: true
    owner_url: https://github.com/kapresoft/kapresoft.github.io
    owner_name: KapreSoft (Antonio Lagnada)

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-last-modified-at

last-modified-at:
  date-format: '%d-%b-%y %T %z'

# seo-tag
author:
  name: Antonio Lagnada
  twitter: deloy72
logo: /assets/images/kapresoft.png