theme: jekyll-theme-leap-day
title: KapreSoft
name: KapreSoft.com
description: The Java Blogger by Antonio Lagnada
layout: kapresoft

exclude:
  - "*.sh"
  - "*.code-workspace"
  - "*.gemspec"
  - "README*.md"
  - ".idea/*"

# set to "dev" so that analytics and adds won't show
env: prod

# OLD Analytics Tracking ID (Deprecated)
# google_analytics: UA-123953282-1

# ----------------
# Google Analytics (V4)
ga:
  enable: true
  tracking_id: G-1EG60WX50K

show_google_ads: true
show_banner: false

excerpt_separator: <!--excerpt-->

# ---------------
# highlighterjs
#  - no line number supper
# Themes: https://github.com/highlightjs/highlight.js/tree/main/src/styles
highlighterjs:
    default_theme: androidstudio

github:
    is_project_page: true
    owner_url: /about-antonio-lagnada.html
    owner_name: KapreSoft (Antonio Lagnada)

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-default-layout

last-modified-at:
  date-format: '%d-%b-%y %T %z'

# seo-tag
author:
  name: Antonio Lagnada
  twitter: deloy72
logo: /assets/images/kapresoft1-210x.png

twitter:
  username: deloy72
  card: summary

